[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "01"
path = "src/bin/01.rs"

[[bin]]
name = "02"
path = "src/bin/02.rs"

[[bin]]
name = "03"
path = "src/bin/03.rs"
